# Generated by Django 4.2.1 on 2023-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.CharField(choices=[('BRS', 'Barisal'), ('CTG', 'Chittagong'), ('DHK', 'Dhaka'), ('KLN', 'Khulna'), ('MMS', 'Mymensingh'), ('RJS', 'Rajshahi'), ('RGP', 'Rangpur'), ('SYL', 'Sylhet')], max_length=20),
        ),
    ]
