# Generated by Django 4.2.1 on 2023-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0002_alter_location_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplace',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
