# Generated by Django 4.2.1 on 2023-07-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0005_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
