# Generated by Django 4.2.1 on 2023-07-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0006_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourplace',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
