# Generated by Django 4.2.1 on 2023-07-13 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0007_alter_tourplace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplace',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
